name = "axvara"
compatibility_date = "2026-08-31"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "axvara-db"
database_id = "c21453bf-68ab-4efd-8b0d-22fb360c4f33"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "axvara-assets"
