-- Local-only editorial fixtures. Never run automatically on production.
-- The stable slug and INSERT OR IGNORE make this seed idempotent.
INSERT OR IGNORE INTO articles (slug,title,excerpt,content,status,author_type,author_name,source_urls,is_published,created_at,updated_at) VALUES
('cara-memilih-ai-untuk-kuliah','Cara Memilih AI untuk Kuliah','Panduan praktis memilih tool AI untuk riset, menulis, dan presentasi.','## Mulai dari kebutuhan\nPilih tool berdasarkan tugas, bukan tren.\n\n## Cek sumber\nSelalu verifikasi jawaban AI dengan sumber primer.','draft','seed','AXVARA Editorial','["https://www.openai.com"]',0,datetime('now'),datetime('now')),
('workflow-content-creator','Workflow Content Creator yang Lebih Cepat','Rangka kerja sederhana untuk merencanakan, membuat, dan mengevaluasi konten.','## Sistem lebih penting\nGunakan checklist yang bisa diulang untuk setiap konten.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('hemat-token-ai','Cara Hemat Token Saat Pakai AI','Langkah kecil untuk menjaga biaya penggunaan AI tetap terkendali.','## Ringkas konteks\nBerikan konteks yang relevan saja dan gunakan prompt yang spesifik.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('cek-fakta-jawaban-ai','Cara Cek Fakta Jawaban AI','AI membantu memulai riset, tetapi bukan pengganti verifikasi.','## Utamakan sumber primer\nBandingkan jawaban dengan dokumentasi atau situs resmi.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('prompt-untuk-desain','Prompt Desain yang Jelas','Struktur prompt untuk menghasilkan brief desain yang mudah dieksekusi.','## Jelaskan tujuan\nSebutkan audiens, format, dan batasan visual.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('notion-untuk-freelancer','Notion untuk Freelancer','Atur proyek dan klien dengan dashboard yang tidak berlebihan.','## Satu sumber kebenaran\nSimpan brief, status, dan tenggat dalam satu database.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('persiapan-presentasi','Persiapan Presentasi Lebih Rapi','Cara menyiapkan presentasi singkat yang tetap meyakinkan.','## Mulai dari pesan utama\nSatu slide sebaiknya menyampaikan satu ide utama.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('belajar-coding-dengan-ai','Belajar Coding dengan AI','Gunakan AI sebagai teman diskusi, bukan mesin salin-tempel.','## Pahami sebelum pakai\nMinta penjelasan kode dan uji setiap perubahan.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('manajemen-file-kreator','Manajemen File untuk Kreator','Struktur folder sederhana agar aset mudah ditemukan.','## Nama file konsisten\nGunakan tanggal, proyek, dan versi dalam nama file.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('pilih-tool-produktivitas','Memilih Tool Produktivitas','Tool terbaik adalah yang dipakai rutin oleh tim.','## Hindari duplikasi\nTentukan satu tempat untuk tugas dan dokumentasi.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('dasar-keamanan-akun','Dasar Keamanan Akun Digital','Kebiasaan kecil untuk menjaga akun premium tetap aman.','## Gunakan sandi unik\nAktifkan autentikasi dua langkah bila tersedia.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('riset-produk-digital','Riset Sebelum Membeli Produk Digital','Pertanyaan yang perlu dijawab sebelum memilih langganan digital.','## Bandingkan kebutuhan\nFokus pada fitur yang benar-benar akan digunakan.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('brief-desain-yang-baik','Membuat Brief Desain yang Baik','Brief yang jelas mengurangi putaran revisi.','## Sertakan contoh\nTunjukkan referensi dan alasan memilihnya.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('otomasi-tugas-berulang','Otomasi Tugas Berulang','Identifikasi tugas kecil yang aman untuk diotomasi.','## Mulai kecil\nOtomasi satu langkah yang sering diulang.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('menulis-copy-produk','Menulis Copy Produk yang Jujur','Copy yang baik menjelaskan manfaat tanpa klaim berlebihan.','## Spesifik dan terukur\nJelaskan untuk siapa produk tersebut berguna.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('strategi-belajar-mandiri','Strategi Belajar Mandiri','Cara membangun ritme belajar yang realistis setiap minggu.','## Buat target kecil\nSatu sesi fokus lebih baik dari rencana besar yang tertunda.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('review-tool-sebelum-renew','Review Tool Sebelum Renew','Evaluasi langganan sebelum memperpanjangnya.','## Lihat pemakaian\nCatat fitur yang benar-benar dipakai bulan ini.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('kolaborasi-tim-kecil','Kolaborasi Tim Kecil','Praktik sederhana untuk menjaga pekerjaan tim tetap jelas.','## Tetapkan pemilik\nSetiap tugas harus memiliki satu penanggung jawab.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('dasar-analitik-konten','Dasar Analitik Konten','Metrik sederhana untuk menilai apakah konten membantu audiens.','## Jangan terpaku angka tunggal\nLihat pola interaksi dan kualitas respons.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now')),
('checklist-launch-proyek','Checklist Launch Proyek','Checklist ringkas sebelum halaman atau produk baru dipublikasikan.','## Uji alur utama\nPastikan pengguna dapat menyelesaikan tugas penting tanpa hambatan.','draft','seed','AXVARA Editorial','[]',0,datetime('now'),datetime('now'));
